services:
  pihome:
    image: pihome
    build: .
    restart: always
    devices:
      - "/dev/mem:/dev/mem"
    privileged: true
    ports:
      - 5000:5000
    environment:
      - NETWORK_TO_SCAN=${NETWORK_TO_SCAN}
    volumes:
    - app_data:/application
    
  prometheus:
    image: prom/prometheus:v2.16.0
    user: root
    volumes:
      - prometheus_data:/etc/prometheus/
      - /var/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    extra_hosts:
      - pihome:${HOST_IP}
    depends_on:
      - pihome
    restart: always

  grafana:
    image: grafana/grafana:6.6.2
    depends_on:
      - prometheus
    ports:
      - 80:3000
    volumes:
      - grafana_config:/etc/grafana
      - grafana_data:/var/lib/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
  app_data:
    driver: local
    driver_opts:
      type: none
      device: ./application
      o: bind  
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      device: ./prometheus
      o: bind
  grafana_config:
    driver: local
    driver_opts:
      type: none
      device: ./grafana
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: ./grafana_data
      o: bind